import { Routes } from '@angular/router';
import { MainPage } from './features/main-page/main-page';
import { Login } from './features/login/login';
import { Signup } from './features/signup/signup';
import { Profile } from './features/profile/profile';
import { PropertyPage } from './features/property-page/property-page';
import { Favorites } from './features/favorites/favorites';
import { ManagementPage } from './features/management-page/management-page';
import { PropertyFormPage } from './features/property-form-page/property-form-page';
import { MyReservations } from './features/my-reservations/my-reservations';
import { UserManagement } from './features/user-management/user-management';
import { ReservationManagement } from './features/reservation-management/reservation-management';
import { PaymentManagement } from './features/payment-management/payment-management';
import { ContractManagement } from './features/contract-management/contract-management';
import { StatsPage } from './features/stats-page/stats-page';
import { VerifyEmail } from './features/verify-email/verify-email';
import { CheckEmail } from './features/check-email/check-email';
import { ForgotPassword } from './features/forgot-password/forgot-password';
import { ResetPassword } from './features/reset-password/reset-password';

export const routes: Routes = [
  { path: '', component: MainPage },
  { path: 'catalogue', component: MainPage },
  { path: 'favoris', component: Favorites },
  { path: 'login', component: Login },
  { path: 'verify-email', component: VerifyEmail },
  { path: 'check-email', component: CheckEmail },
  { path: 'signup', component: Signup },
  { path: 'forgot-password', component: ForgotPassword },
  { path: 'reset-password', component: ResetPassword },
  { path: 'profile', component: Profile },
  { path: 'real-estate/:id', component: PropertyPage },
  { path: 'management', component: ManagementPage },
  { path: 'management/new', component: PropertyFormPage },
  { path: 'management/:id/edit', component: PropertyFormPage },
  { path: 'reservations/my', component: MyReservations },
  { path: 'admin/users', component: UserManagement },
  { path: 'reservations/manage', component: ReservationManagement },
  { path: 'payments/manage', component: PaymentManagement },
  { path: 'contracts/manage', component: ContractManagement },
  { path: 'stats', component: StatsPage },
  { path: '**', redirectTo: '' },
];
