import { betterAuth } from 'better-auth';
import { Pool } from 'pg';
import { z } from 'zod';
import { sendMail } from './mailer';
import {
  verificationEmailTemplate,
  resetPasswordEmailTemplate,
} from './email-templates';

const googleClientId = process.env.GOOGLE_CLIENT_ID;
const googleClientSecret = process.env.GOOGLE_CLIENT_SECRET;

export const auth = betterAuth({
  baseURL: process.env.BACKEND_URL ?? 'http://localhost:3000',
  basePath: '/api/auth',

  database: new Pool({
    connectionString: process.env.DATABASE_URL, // Use DATABASE_URL for connection
  }),

  emailAndPassword: {
    enabled: true,
    minPasswordLength: 8,
    requireEmailVerification: true,

    sendResetPassword: async ({ user, url }) => {
      const token = url.split('/').pop()?.split('?')[0] ?? '';
      const path =
        process.env.FRONTEND_RESET_PASSWORD_PATH ?? '/reset-password';
      const frontendUrl = `${process.env.FRONTEND_URL ?? 'http://localhost:4200'}${path}?token=${token}`;

      await sendMail({
        to: user.email,
        subject: 'Réinitialisation de votre mot de passe — NestHome',
        html: resetPasswordEmailTemplate(frontendUrl),
      });
    },
  },

  emailVerification: {
    sendOnSignUp: true,
    autoSignInAfterVerification: false, // Do not auto sign-in after email verification for better security
    expiresIn: 60 * 60 * 24,
    sendVerificationEmail: async ({ user, url }) => {
      // Extract the token from the URL generated by better-auth
      const token = new URL(url).searchParams.get('token') ?? '';

      // Get the frontend path for email verification from environment variable or use default
      const path = process.env.FRONTEND_VERIFY_EMAIL_PATH ?? '/verify-email';

      // Construct the frontend URL for email verification, including the token as a query parameter
      const frontendUrl = `${process.env.FRONTEND_URL ?? 'http://localhost:4200'}${path}?token=${token}`;

      await sendMail({
        to: user.email,
        subject: 'Confirmez votre adresse email — NestHome',
        html: verificationEmailTemplate(frontendUrl),
      });
    },
  },

  ...(googleClientId && googleClientSecret
    ? {
        socialProviders: {
          google: {
            clientId: googleClientId,
            clientSecret: googleClientSecret,
            prompt: 'select_account',
          },
        },
      }
    : {}),

  user: {
    additionalFields: {
      // Additional custom field 'role' to the user table
      role: {
        type: 'string',
        required: false,
        defaultValue: 'user',
        validator: {
          input: z.enum(['admin', 'agent', 'user']), // Validate role values
        },
        input: false, // Hide from user input forms
      },
      // Additional custom field 'isActive' to the user table
      isActive: {
        type: 'boolean',
        required: false,
        defaultValue: true, // Default to active users
        validator: {
          input: z.boolean().optional(),
        },
        input: false, // Hide from user input forms
      },
    },
  },

  session: {
    enabled: true,
    expiresIn: 60 * 60 * 24 * 1, // 1 day
  },

  debug: true, // Enable debug mode for development

  trustedOrigins: [
    process.env.BACKEND_URL ?? 'http://localhost:3000',
    process.env.FRONTEND_URL ?? 'http://localhost:4200',
  ],
});
